# Generated by Django 5.0.6 on 2024-08-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_pengaduan_evidence_alter_pengaduan_lokasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='akun_sso',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='npm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='like',
            name='npm',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='npm',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
