# Generated by Django 5.1 on 2024-09-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_pengaduan_evidence_alter_pengaduan_lokasi'),
        ('jwt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='user',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan', to='jwt.ssoaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jwt.ssoaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='evidence',
            field=models.URLField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pengaduan',
            name='lokasi',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
