# Generated by Django 5.1 on 2024-09-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_remove_pengaduan_user_pengaduan_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='tanggal_post',
            field=models.DateTimeField(default=True),
        ),
    ]
