# Generated by Django 5.0.6 on 2024-08-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_statusupdate_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusUpdate',
        ),
    ]
