# Generated by Django 5.1 on 2024-09-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_alter_pengaduan_tanggal_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengaduan',
            name='status',
            field=models.CharField(choices=[('UNRESOLVED', 'Unresolved'), ('RESOLVED', 'Resolved'), ('REPORTED', 'Reported')], default='UNRESOLVED', max_length=10),
        ),
    ]
