# Generated by Django 5.1 on 2024-09-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_alter_pengaduan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
