# Generated by Django 5.1 on 2024-10-29 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0008_alter_like_akun_sso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='evidence',
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('pengaduan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='issue_tracker.pengaduan')),
            ],
        ),
    ]
