# Generated by Django 5.1 on 2024-11-03 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0009_remove_pengaduan_evidence_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tanggal_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
