# Generated by Django 5.1 on 2024-11-17 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0011_pengaduanstatuschange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduanstatuschange',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pengaduan_status_changes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
