# Generated by Django 5.1 on 2024-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0012_pengaduanstatuschange_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduanstatuschange',
            old_name='status',
            new_name='new_status',
        ),
        migrations.AddField(
            model_name='pengaduanstatuschange',
            name='old_status',
            field=models.CharField(default='RESOLVED', max_length=10),
            preserve_default=False,
        ),
    ]
