# Generated by Django 5.1 on 2024-11-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0013_rename_status_pengaduanstatuschange_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='kategori',
            field=models.CharField(choices=[('FINANSIAL', 'Finansial'), ('KEKERASAN_SEKSUAL', 'Kekerasan Seksual'), ('FASILITAS', 'Fasilitas'), ('AKADEMIS', 'Akademis'), ('LAINNYA', 'Lainnya')], default='LAINNYA', max_length=64),
        ),
    ]
