# Generated by Django 5.2.7 on 2025-11-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinary_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='video',
        ),
    ]
