# Generated by Django 5.2.7 on 2025-11-29 13:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinary_app', '0002_rename_url_image_image_rename_url_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=cloudinary.models.CloudinaryField(default='Something', max_length=255),
            preserve_default=False,
        ),
    ]
