# Generated by Django 5.2.7 on 2025-11-29 13:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinary_app', '0003_remove_image_image_remove_video_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
