# Generated by Django 5.2.7 on 2025-11-29 13:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinary_app', '0004_alter_image_image_url_alter_video_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True),
        ),
    ]
