# Generated by Django 6.0 on 2026-01-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinary_app', '0006_alter_image_image_url_alter_video_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video',
        ),
    ]
