# Generated by Django 5.1 on 2024-11-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='biro_name',
            field=models.CharField(default='Biro Humas', max_length=255),
            preserve_default=False,
        ),
    ]
