# Generated by Django 5.1 on 2024-11-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0002_event_biro_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
    ]
