# Generated by Django 5.0.6 on 2024-08-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSOAccount',
            fields=[
                ('npm', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('short_faculty', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
            ],
        ),
    ]
