# Generated by Django 5.1.4 on 2025-01-01 09:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jwt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEMMember',
            fields=[
                ('sso_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jwt.ssoaccount')),
                ('role', models.CharField(choices=[('STAFF', 'Staff'), ('BPH', 'Bph'), ('KOOR', 'Koor')], default='STAFF', max_length=5)),
                ('img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField()),
            ],
        ),
    ]
