# Generated by Django 5.1.4 on 2025-01-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birdept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('galeri', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='bemmember',
            name='birdept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='best_staff.birdept'),
        ),
        migrations.CreateModel(
            name='NPM_Whitelist',
            fields=[
                ('npm', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('birdept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npm_whitelists', to='best_staff.birdept')),
            ],
        ),
        migrations.AddField(
            model_name='bemmember',
            name='npm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='best_staff.npm_whitelist'),
        ),
    ]
