# Generated by Django 5.1 on 2025-01-09 15:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0003_alter_event_end'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('birdept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='best_staff.birdept')),
                ('voted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted', to='best_staff.bemmember')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='best_staff.bemmember')),
            ],
        ),
    ]
