# Generated by Django 5.1 on 2025-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('PI', 'PI'), ('STAFF', 'STAFF')], default='STAFF', max_length=5),
        ),
    ]
