# Generated by Django 5.1.4 on 2025-01-12 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0005_vote_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
    ]
