# Generated by Django 5.1 on 2025-01-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0006_remove_vote_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bemmember',
            name='birdept',
        ),
        migrations.AddField(
            model_name='bemmember',
            name='birdept',
            field=models.ManyToManyField(blank=True, to='best_staff.birdept'),
        ),
    ]
