# Generated by Django 5.1 on 2025-01-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0007_remove_bemmember_birdept_bemmember_birdept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bemmember',
            name='npm',
        ),
        migrations.DeleteModel(
            name='NPM_Whitelist',
        ),
    ]
