# Generated by Django 5.2.8 on 2025-11-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0008_remove_bemmember_npm_delete_npm_whitelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdept',
            name='desc',
        ),
        migrations.AddField(
            model_name='birdept',
            name='deskripsi',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='birdept',
            name='displayed_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='birdept',
            name='nama',
            field=models.CharField(max_length=200),
        ),
    ]
