# Generated by Django 5.2.7 on 2025-11-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0009_remove_birdept_desc_birdept_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemmember',
            name='birdept',
            field=models.ManyToManyField(to='best_staff.birdept'),
        ),
    ]
