# Generated by Django 5.2.7 on 2025-12-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('best_staff', '0010_alter_bemmember_birdept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bemmember',
            name='birdept',
            field=models.ManyToManyField(blank=True, to='best_staff.birdept'),
        ),
    ]
