name: Push Docker Image (Staging)

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  DEPLOYMENT_NAME: api
  IMAGE: api
  GAR_LOCATION: us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gcr.io/api:latest
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Build
        run: |-
          docker build \
            --tag ${{ env.GAR_LOCATION }} .

      - name: Publish
        run: |-
          docker push ${{ env.GAR_LOCATION }}
