name: Run Docker Image (Staging)
on:
  workflow_run:
    workflows: ["Push Docker Image (Staging)"]
    types:
      - completed
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          proxy_host: kawung.cs.ui.ac.id
          proxy_username: ${{ secrets.KAWUNG_USERNAME }}
          proxy_passphrase: ${{ secrets.KAWUNG_PASSPHRASE }}
          proxy_port: 12122
          proxy_key: ${{ secrets.KAWUNG_KEY }}
          script: |
            echo 'Connected to server PTI!'
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker ps
            gcloud auth print-access-token | sudo docker login -u oauth2accesstoken --password-stdin us-docker.pkg.dev
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker stop api
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker rm api
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker pull us-docker.pkg.dev/bem-pti-422515/gcr.io/api:latest
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker run -d --name api-staging -p 5000:8000 us-docker.pkg.dev/bem-pti-422515/gcr.io/api:latest \
            -e SECRET_KEY='h^z13$qr_s_wd65@gnj7a=xs7t05$w7q8!x_8zsld#' \
            -e DATABASE_NAME='staging' \
            -e DATABASE_USER='staging_owner' \
            -e DATABASE_PASS='DZgfh8pS5CeY' \
            -e DATABASE_HOST='ep-muddy-art-a1awil8x-pooler.ap-southeast-1.aws.neon.tech' \
            -e DATABASE_PORT='5432'
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker ps
